name: Go

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.18', '1.17', '>=1.18']
        os: ['ubuntu-latest',    'ubuntu-22.04']
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go_version }}

    - name: Build-DB
      run: docker-compose build    || echo "Failed to build Docker Compose environment"

    - name: Create-DB
      run: docker-compose up -d || echo "Failed to create database"

    - name: Test
      run: go test -v main_test.go || echo "Tests failed"

  build:
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-22.04']
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: go build -v main.go || echo "Build failed"
