name: Go Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v3   
      with:
        go-version: 1.19
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Test with coverage
      run: |
        go test -coverprofile=coverage.txt -covermode=atomic ./...
        bash <(curl -s https://raw.githubusercontent.com/golang/go/master/src/cmd/cover/cover.bash)
